= Node.js Client for UBER Hypermedia Type
:toc:
:numbered:

== Document Status
Author::
  Irakli Nadareishvili
Status::
  *[white red-background]#Working Draft#*

////
  *[white blue-background]#Release Candidate#*
  *[white green-background]#Released#*
////

Last Updated::
  {docdate}

== General
Node.js client is an implementation of an SDK-level client for the http://uberhypermedia.org[UBER hypermedia message format]

== Design Goals
Minimal, robust, extensible

[source,javascript]
----
var client = require('uberclient')
  , token  = '1234567890'; // You'd normally get this from a separate OAuth2 workflow

client.authProvider(new client.tokenAuthProvider('mytoken'));
request('http://api.froyo.io', function (error, message) {
  if (!error) {
    // do something with message
  }
})
----

== API Documentation

=== Module: uberclient

==== Methods

authProvider(providerFunction)::
  sets the authorization provider that will be used henceforth. Provider function accepts +options+ javascript object used 
  for configuring specific type of a provider. UberClient pre-defines two types of providers (HTTP OAuth2-compatible, 
  bearer token-based and HTTP URL query-param based). Any provider function can be passed to extend this functionality. THe 
  implementing function must expose preprocessRequest(request) function that will be called before a request is fired.
  
authProviderTokenBased({"token" : "...", "header-field" : "..."})::
   OAuth-2 compatible. `header-field` defaults to `Bearer` resulting in an HTTP request header field of the form: `Authorization: Bearer xxxxxxxxxxxxxx`
  

authProviderApikeyBased({"apikey" : "...", "query-field" : "..."})::
   API Key compatible. `query-field` defaults to `key` resulting in an HTTP request query field of the form: `?key=xxxx` or `&key=xxxx`
  

=== Class: Message

=== Class: Message

==== Properties

+version+::
  returns the version of the UBER format used in this message

==== Methods

Message(message)::
constructor. Initialized by a properly-formatted UBER message serialized in XML or JSON.

data()::
returns an array of `Data` elements
  
error()::
returns an array of `Data` elements
  
raw()::
returns the raw original text of the message (XML or JSON). Response object is of the form: 

rawFormat()::
returns the format of the original text of the message ('xml' or 'json')

toJSON()::
serializes the current message object into UBER JSON representation

toXML()::
serializes the current message object into UBER XML representation

=== Class: Data

==== Properties

==== Methods

query(selector [, context])::
returns a new Data element containing child Data elemenst found in the context Data object, filtered based on passed argument(s). 
Inpsired by http://api.jquery.com/jQuery/[jQuery()]

    +selector+;;
      is a JSON object, value of which is a regular expression, and key is one of the following three options:
      +
      - +id+ matches by ID
      - +name+ matches by name
      - +rel+ matches by any of the rels. 
+     
[NOTE]
A special case of `{"*" : "*"}` stands for: "match any elements"
+
.Example
[source,javascript]
----
var locationdata = data.query({"rel" : "loc+*"}).query({"name" : "eiffel"});
----
    +context+;;
      can have one of two values:
      - 'children' (default)
      - 'first-child'
      - 'last-child'
      - 'depth-n' where n is a number 1-10 (infinite depth is prohibited)
    
=== Class: LinkRelation

==== Properties

1. name

==== Methods

1. isURL() - is link relation name a proper URL?
2. resolve() - resolve the link relation, if it is a proper URL

=== Class: Parser

==== Methods

  Constructors(message)::
  detect()::
  detects the source serialization format of a message: JSON, XML or invalid (for now)
  transcode(message, inputFormat = null)::
  transcodes any supported input format (for now: XML) to UBER/JSON
  parse(message, inputFormat = null)::
  parses any supported input format (XML or JSON, for now) into UBER Message object graph. Parsing is always lazy: only first level of the hierarchy is parsed.


